trajectory_eval_distance:
  min_dist_cat: 64
  max_dist_cat: 64
trajectory_eval_len_traj_pred: 32
trajectory_eval_context_size: 4
eval_context_size: 4
traj_stride: 80

eval_datasets:
  sekai_new:
    data_folder: data/sekai_new
    test: data/splits/sekai_new/test
    goals_per_obs: 4
