action_stats:
  min: [-2.5, -4, -3] # [min_dx, min_dy, min_dz]
  max: [5, 4, 3] # [max_dx, max_dy, max_dz]

recon:
  metric_waypoint_spacing: 0.25 # average spacing between waypoints (meters)

scand:
  metric_waypoint_spacing: 0.38

tartan_drive:
  metric_waypoint_spacing: 0.72

go_stanford:
  metric_waypoint_spacing: 0.12

sacson:
  metric_waypoint_spacing: 0.255

wuhan:
  metric_waypoint_spacing: 1.82

wuhan_auto:
  metric_waypoint_spacing: 1.26

airvln:
  metric_waypoint_spacing: 3.29

airvln_airspace:
  metric_waypoint_spacing: 3.23

airvln_1episode:
  metric_waypoint_spacing: 3.09