traj_stride: 80

eval_distance:
  eval_min_dist_cat: -64
  eval_max_dist_cat: 64
eval_len_traj_pred: 16
eval_context_size: 16

eval_datasets:
  airvln_16:
    data_folder: data/airvln_16
    test: data/splits/airvln_16/test
    goals_per_obs: 4
